import { readdirSync, writeFileSync, statSync } from 'node:fs';
import { join, basename, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const specsDir = join(__dirname, '..', 'specs');

interface SpecEntry {
  category: string;
  slug: string;
  relPath: string; // e.g. "ip-intelligence/ip-locator.json"
}

function walkSpecs(dir: string, category?: string): SpecEntry[] {
  const entries: SpecEntry[] = [];
  for (const name of readdirSync(dir).sort()) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      entries.push(...walkSpecs(full, name));
    } else if (name.endsWith('.json')) {
      const slug = basename(name, '.json');
      const relPath = relative(specsDir, full).replace(/\\/g, '/');
      entries.push({ category: category ?? 'uncategorized', slug, relPath });
    }
  }
  return entries;
}

const specs = walkSpecs(specsDir);

const imports = specs.map((s, i) => {
  return `import _s${i} from '../specs/${s.relPath}' with { type: 'json' };`;
});

const specEntries = specs.map((s, i) => {
  return `  '${s.slug}': _s${i} as OpenAPISpec,`;
});

const slugs = specs.map(s => `'${s.slug}'`);

const categories = [...new Set(specs.map(s => s.category))].sort();

const categoryEntries = categories.map(cat => {
  const catSlugs = specs.filter(s => s.category === cat).map(s => `'${s.slug}'`);
  return `  '${cat}': [${catSlugs.join(', ')}],`;
});

const content = `// AUTO-GENERATED by scripts/generate-manifest.ts — do not edit manually
import type { OpenAPISpec } from './types.js';

${imports.join('\n')}

export const SPECS: Record<string, OpenAPISpec> = {
${specEntries.join('\n')}
};

export const SPEC_SLUGS: string[] = [${slugs.join(', ')}];

export const SPEC_CATEGORIES: string[] = [${categories.map(c => `'${c}'`).join(', ')}];

export const SPECS_BY_CATEGORY: Record<string, string[]> = {
${categoryEntries.join('\n')}
};
`;

const outPath = join(__dirname, '..', 'src', 'manifest.ts');
writeFileSync(outPath, content, 'utf-8');
console.log(`Generated manifest with ${specs.length} specs across ${categories.length} categories`);
